In [1]:
import pandas as pd
import numpy as np
from pandas.api.types import CategoricalDtype
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_log_error
from catboost import CatBoostRegressor, Pool

cols = [
    # Для идентификации
    "date",

    # таргет
    "units",

    # прошлое
    "units_yesterday", "units_prev_week",
    # "rolling_mean_4w", - кривая фича, переделать, она не должна включать день предсказания

    # категориальные
    "store_code", "store_item_code",

    # погода (float32)
    "tmax", "tmin", "tavg", "depart", "dewpoint", "wetbulb", "heat", "cool",
    "sunrise", "sunset",
    "snowfall", "preciptotal", "stnpressure", "sealevel",
    "resultspeed", "resultdir", "avgspeed",

    # календарь и флаги (int16)
    "year", "week", "BCFG", "BLDU", "BLSN", "BR", "DU", "DZ", "FG", "FU",
    "FZDZ", "FZFG", "FZRA", "GR", "GS", "HZ", "MIFG", "PL", "PRFG", "RA",
    "SG", "SN", "SQ", "TS", "TSRA", "TSSN", "UP", "VCFG", "VCTS",
    "day_of_week", "month", "is_weekend", "is_holiday",
    "rain_streak", "dry_streak",

    # look‑ahead
    "avg_temp_next_day", "rain_next_day", "days_to_holiday"
]

dtypes = {
    # целевой
    "units": "int16",        # -32 768 … 32 767

    # Для идентификации
    "date": "object",

    # прошлое → float32
    **{c: "float32" for c in [
        "units_yesterday", "units_prev_week", "rolling_mean_4w",
    ]},
    

    # категориальные коды
    "store_code": "category",
    "store_item_code": "category",

    # погода → float32
    **{c: "float32" for c in [
        "tmax","tmin","tavg","depart","dewpoint","wetbulb","heat","cool",
        "sunrise","sunset",
        "snowfall","preciptotal","stnpressure","sealevel",
        "resultspeed","resultdir","avgspeed",
        "avg_temp_next_day","rain_next_day",
    ]},

    # календарные/флаговые → int16
    **{c: "int16" for c in [
        "year","week","day_of_week","month",
        "is_weekend","is_holiday","rain_streak","dry_streak",
        "BCFG","BLDU","BLSN","BR","DU","DZ","FG","FU","FZDZ","FZFG",
        "FZRA","GR","GS","HZ","MIFG","PL","PRFG","RA","SG","SN","SQ",
        "TS","TSRA","TSSN","UP","VCFG","VCTS", "days_to_holiday",
    ]},
}

full_table_df = pd.read_csv(
    "./data/big_full_table.csv",
    usecols=cols,
    dtype=dtypes,
)
full_table_df['date'] = pd.to_datetime(full_table_df['date'])

In [2]:
from catboost import CatBoostRegressor

model = CatBoostRegressor()
model.load_model(f"../ml-models/CatBoost v1.cbm")

In [3]:
full_table_df[model.feature_names_][full_table_df[model.feature_names_].isna().any(axis=1)]

Empty DataFrame
Columns: [store_code, store_item_code, units_yesterday, units_prev_week, tmax, tmin, tavg, depart, dewpoint, wetbulb, heat, cool, sunrise, sunset, snowfall, preciptotal, stnpressure, sealevel, resultspeed, resultdir, avgspeed, year, week, BCFG, BLDU, BLSN, BR, DU, DZ, FG, FU, FZDZ, FZFG, FZRA, GR, GS, HZ, MIFG, PL, PRFG, RA, SG, SN, SQ, TS, TSRA, TSSN, UP, VCFG, VCTS, day_of_week, month, is_weekend, is_holiday, rain_streak, dry_streak, avg_temp_next_day, rain_next_day, days_to_holiday]
Index: []

[0 rows x 59 columns]

In [4]:
cat_cols = ["store_code", "store_item_code"]
test_pool   = Pool(full_table_df[model.feature_names_],  full_table_df['units'],  cat_features=cat_cols)

# Предсказываем.
Y_production = model.predict(test_pool)

In [6]:
df = pd.DataFrame({'y_pred': Y_production, 'units': full_table_df['units'], 'date': full_table_df['date'], 'store_item_code': full_table_df['store_item_code']})
df.loc[df['y_pred'] < 0, 'y_pred'] = 0

# Выводим случайные 40 строк
display(df.sample(40))

           y_pred  units       date store_item_code
125617   0.161990      0 2013-05-21         s37-i38
115386   0.203479      0 2013-04-03         s45-i50
215659  10.787509      8 2014-07-25         s19-i83
50483   88.120361     78 2012-07-21           s4-i9
3678     0.000000      0 2012-01-15         s5-i105
70024   67.631445     50 2012-10-06          s24-i6
192852  53.498205    116 2014-04-05          s24-i6
127434  12.357323     14 2013-05-31          s4-i27
95750    7.506490     10 2013-01-16         s19-i83
230924   0.444547      0 2014-10-07         s35-i63
36205    0.362948      0 2012-05-26         s32-i58
134851  49.740131     42 2013-07-08         s37-i45
69543    0.837976      0 2012-10-04           s3-i2
157036   0.332544      0 2013-10-27         s19-i15
158575   0.897460      3 2013-11-03         s30-i65
120761   0.535909      0 2013-04-29         s25-i84
83511    0.000000      0 2012-11-28         s19-i88
28482   59.582882     68 2012-04-25          s20-i5
226464   0.000000      0 2014-09-16         s11-i86
84383   91.951013     78 2012-12-01         s37-i45
196051   0.000000      0 2014-04-19         s21-i91
187921   5.606447      4 2014-03-14         s14-i25
156875   0.098933      0 2013-10-26         s33-i93
11009   48.755484     35 2012-02-14         s32-i45
210243  20.386622     22 2014-06-26          s23-i5
30604    1.024938      5 2012-05-03          s5-i32
49870   39.096198     44 2012-07-19         s22-i68
72561   38.514524     44 2012-10-16          s21-i5
75517    6.825390     23 2012-10-27          s5-i93
143155   0.626576      0 2013-08-22         s24-i60
159915   0.000000      0 2013-11-09         s3-i102
235120   0.000000      0 2014-10-28         s25-i81
22046    0.716748      0 2012-03-30         s19-i39
110877   0.000000      0 2013-03-16         s33-i85
142103   9.343934     10 2013-08-18          s1-i28
147849  22.984110     16 2013-09-12         s16-i16
44747    0.000000      0 2012-06-29         s19-i39
194706   0.000000      0 2014-04-13         s19-i93
108608  44.876153     60 2013-03-07         s37-i45
48392    3.202495      1 2012-07-13         s31-i93

In [14]:
full_table_df['units_pred'] = Y_production
full_table_df.to_csv('./data/prediction_real_weather-0.1.csv', index=False)